version: '3'

services:
  loadbalancer:
    build:
      context: ./loadbalancer
    ports:
      - "80:80"
      - "443:443"
    networks:
      - dmz1_network
      - dmz2_network

  web1:
    build:
      context: ./web1
    networks:
      - dmz1_network

  web2:
    build:
      context: ./web2
    networks:
      - dmz1_network

  db:
    image: mysql:latest  # Utilisez l'image de votre choix
    environment:
      MYSQL_ROOT_PASSWORD: your_password
    networks:
      - dmz2_network

networks:
  dmz1_network:
    ipam:
      config:
        - subnet: 192.168.50.0/24

  dmz2_network:
    ipam:
      config:
        - subnet: 10.0.50.0/24
